[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unnamed-geography-game"
dynamic = ["version"]
description = 'Simple geography quiz for the terminal'
readme = "README.md"
requires-python = ">=3.14"
keywords = []
authors = [
  { name = "Øyvind I. Berntsen", email = "oi.berntsen@gmail.com" },
]

dependencies = [
    "igraph>=1.0.0",
    "textual>=8.2.8",
    "textual-autocomplete>=4.0.6",
    "textual-dev>=1.8.0",
]

[project.scripts]
unnamed-geography-game = "unnamed_geography_game.app:main"

[tool.hatch.version]
path = "src/unnamed_geography_game/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/unnamed_geography_game tests}"

[tool.coverage.run]
source_pkgs = ["unnamed-geography-game", "tests"]
branch = true
parallel = true
omit = [
  "src/unnamed_geography_game/__about__.py",
]

[tool.coverage.paths]
unnamed-geography-game = ["src/unnamed_geography_game", "*/unnamed-geography-game/src/unnamed_geography_game"]
tests = ["tests", "*/unnamed-geography-game/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
